Change default exportTimeout to P7D
Because after Beam SDK 2.14, `PT0S` is no longer valid:

```
[main] ERROR com.spotify.dbeam.jobs.ExceptionHandling - Failure:
java.lang.IllegalArgumentException: maxCumulativeBackoff PT0S must be at least 1 millisecond
        at org.apache.beam.vendor.guava.v20_0.com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
        at org.apache.beam.sdk.util.FluentBackoff.withMaxCumulativeBackoff(FluentBackoff.java:131)
        at org.apache.beam.runners.dataflow.DataflowPipelineJob.getMessagesBackoff(DataflowPipelineJob.java:251)
        at org.apache.beam.runners.dataflow.DataflowPipelineJob.waitUntilFinish(DataflowPipelineJob.java:280)
        at org.apache.beam.runners.dataflow.DataflowPipelineJob.waitUntilFinish(DataflowPipelineJob.java:224)
        at org.apache.beam.runners.dataflow.DataflowPipelineJob.waitUntilFinish(DataflowPipelineJob.java:183)
        at com.spotify.dbeam.beam.BeamHelper.waitUntilDone(BeamHelper.java:45)
        at com.spotify.dbeam.jobs.JdbcAvroJob.runAndWait(JdbcAvroJob.java:135)
        at com.spotify.dbeam.jobs.JdbcAvroJob.runExport(JdbcAvroJob.java:141)
        at com.spotify.dbeam.jobs.JdbcAvroJob.main(JdbcAvroJob.java:148)
```